# Generated by Django 4.2.2 on 2023-07-04 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('A-', 'A-'), ('O+', 'O+'), ('O-', 'O-')], max_length=10)),
                ('contact_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('location', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DonationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time_slot', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(null=True)),
                ('photo', models.ImageField(blank=True, upload_to='users/%Y/%m/%d/')),
                ('availability', models.CharField(choices=[('Anyday', 'Any Day'), ('Weekdays', 'Week Days'), ('Weekends', 'Weekends')], default='Anyday', max_length=200)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='Male', max_length=100)),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('A-', 'A-'), ('O+', 'O+'), ('O-', 'O-')], default='A+', max_length=100)),
                ('city', models.CharField(choices=[('Baragoi', 'Baragoi'), ('Bondo', 'Bondo'), ('Bungoma', 'Bungoma'), ('Busia', 'Busia'), ('Butere', 'Butere'), ('Dadaab', 'Dadaab'), ('Diani Beach', 'Diani Beach'), ('Eldoret', 'Eldoret'), ('Emali', 'Emali'), ('Embu', 'Embu'), ('Garissa', 'Garissa'), ('Gede', 'Gede'), ('Hola', 'Hola'), ('Homa Bay', 'Homa Bay'), ('Isiolo', 'Isiolo'), ('Kitui', 'Kitui'), ('Kibwezi', 'Kibwezi'), ('Kajiado', 'Kajiado'), ('Kakamega', 'Kakamega'), ('Kakuma', 'Kakuma'), ('Kapenguria', 'Kapenguria'), ('Kericho', 'Kericho'), ('Kiambu', 'Kiambu'), ('Kilifi', 'kilifi'), ('Kisii', 'Kisii'), ('Kisumu', 'Kisumu'), ('Kitale', 'Kitale'), ('Lamu', 'Lamu'), ('Langata', 'Langata'), ('Litein', 'Litien'), ('Lodwar', 'Lodwar'), ('Lokichoggio', 'Lokichoggio'), ('Londiani', 'Londiani'), ('Machakos', 'Machakos'), ('Malindi', 'Malindi'), ('Mandera', 'Mandera'), ('Maralal', 'Maralal'), ('Marsabit', 'Marsabit'), ('Meru', 'Meru'), ('Mombasa', 'Mombasa'), ('Moyale', 'Moyale'), ('Mtwapa', 'Mtwapa'), ('Mumias', 'Mumias'), ('Muranga', 'Muranga'), ('Nairobi', 'Nairobi'), ('Naivasha', 'Naivasha'), ('Nakuru', 'Nakuru'), ('Namanga', 'Namanga'), ('Nanyuki', 'Nanyuki'), ('Naro Moru', 'Naro Moru'), ('Narok', 'Narok'), ('Nyahururu', 'Nyahururu'), ('Nyeri', 'Nyeri'), ('Ruiru', 'Ruiru'), ('Siaya', 'Siaya'), ('Thika', 'Thika'), ('Ugunja', 'Ugunja'), ('Vihiga', 'Vihiga'), ('Voi', 'Voi'), ('Wajir', 'Wajir'), ('Watamu', 'Watamu'), ('Webuye', 'Webuye'), ('Wote', 'Wote'), ('Wundanyi', 'Wundanyi')], default='Nairobi', max_length=100)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blood_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.bloodrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recieved_message', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_message', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Donation_Made',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=100)),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('A-', 'A-'), ('O+', 'O+'), ('O-', 'O-')], max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('points_earned', models.IntegerField(default=0)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BloodDonationBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
