# Generated by Django 4.2.1 on 2023-06-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_donor1_delete_donor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor1',
            name='phone_no',
            field=models.CharField(max_length=50),
        ),
    ]
