# Generated by Django 4.2.1 on 2023-06-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_profile_delete_donor'),
    ]

    operations = [
        migrations.CreateModel(
            name='gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_orientation', models.CharField(default='Male', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='availability',
            field=models.CharField(choices=[('Anyday', 'Any Day'), ('Weekdays', 'Week Days'), ('Weekends', 'Weekends')], default='Anyday', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='blood_type',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('A-', 'A-'), ('O+', 'O+'), ('O-', 'O-')], default='A+', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(default='Nairobi', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='Male', max_length=100),
        ),
    ]
