# Generated by Django 4.2.1 on 2023-06-21 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_gender_alter_profile_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='system.gender'),
        ),
    ]
