# Generated by Django 4.2.1 on 2023-06-21 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_alter_profile_gender_delete_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='gender',
            new_name='gender_id',
        ),
    ]
