# Generated by Django 4.2.1 on 2023-06-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_rename_gender_id_profile_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time_slot', models.TimeField()),
            ],
        ),
    ]
