# Generated by Django 4.2.1 on 2023-06-22 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system', '0008_donationschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationschedule',
            name='donor_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
