# Generated by Django 4.2.1 on 2023-06-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_alter_donationschedule_donor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationschedule',
            name='donor_name',
            field=models.CharField(max_length=100),
        ),
    ]
