# Generated by Django 4.2.1 on 2023-06-22 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_alter_donationschedule_donor_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donationschedule',
            old_name='donor_name',
            new_name='name',
        ),
    ]
