# Generated by Django 4.2.1 on 2023-06-22 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_rename_donor_name_donationschedule_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DonationSchedule',
            new_name='DonationsSchedule',
        ),
    ]
