# Generated by Django 4.2.1 on 2023-06-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0012_rename_donationschedule_donationsschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time_slot', models.TimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='DonationsSchedule',
        ),
    ]
