# Generated by Django 4.2.1 on 2023-06-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0015_blooddonationbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default='your number', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='blood_type',
            field=models.CharField(default='A+', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(default='Male', max_length=100),
        ),
    ]
