services:
  # --- MySQL database service ---
  - type: pserv
    name: mysql
    plan: standard
    env: docker
    autoDeploy: false
    disk:
      name: mysql
      mountPath: /var/lib/mysql
      sizeGB: 10
    envVars:
      - fromGroup: mysql

  # --- Django web app service ---
  - type: web
    name: bloodheroes
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      python manage.py migrate && gunicorn system.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: mysql
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: system.settings
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: PYTHON_VERSION
        value: 3.13.0

# --- Environment variables group for MySQL ---
envVarGroups:
  - name: mysql
    envVars:
      - key: MYSQL_DATABASE
        value: highschool
      - key: MYSQL_USER
        value: root
      - key: MYSQL_PASSWORD
        generateValue: true
      - key: MYSQL_ROOT_PASSWORD
        generateValue: true
